server {
    listen 80;
    server_name ada-chat.lapeh.web.id;

    # Arahkan langsung ke folder dist/ hasil build
    root /srv/www/node/ada-chat.lapeh.web.id/ada-chat/dist;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}

