server {
    listen 80;
    server_name ada-chat.lapeh.web.id;

    # Arahkan langsung ke folder dist/ hasil build
    root /opt/patuih/patuih-testing/react-version/dist;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}

